---
version: "2.1"
services:
  quiki:
    build: .
    container_name: quiki
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - ./config:/config
#   ports:                    #If you are runnign this locally uncomment this
#     - 80:80                 #and map ports that you want to use
#     - 443:443 #optional
    restart: unless-stopped
    network: reverse-proxy    # if you run locally you can comment this and
networks:                     # also this whole section    
  reverse-proxy:
    external: yes
